name: Build ARM64 Image with MakeMKV from PPA

on:
  schedule:
    - cron: "0 0 * * 0"
  push:
    paths-ignore:
      - 'manual-build/**'
  workflow_dispatch:

env:
  ENDPOINT: "rix1337/docker-ripper"

jobs:
  build-arm64:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: "${{ secrets.DOCKERUSER }}"
          password: "${{ secrets.DOCKERPASS }}"

      - name: Build and Push ARM64 Image
        uses: docker/build-push-action@v5
        with:
          context: "./"
          file: "./latest/Dockerfile"
          platforms: linux/arm64
          push: true
          tags: |
            ${{ env.ENDPOINT }}:latest-arm64
            ${{ env.ENDPOINT }}:ppa-latest-arm64
